version: '3'
services:
  backend:
    image: social-back
    container_name: backend
    ports:
      - "8080:8080"
    networks:   
      - my_network

  frontend:
    image: social-front
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend


networks:
  my_network:
    driver: bridge