import localFont from "next/font/local";
import "./globals.css";
// import { setupWebSocket } from "./websockets";
// import { GetCookieValue } from "./Utils/getCookieValue";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Aura Networking",
  description: "Generated by create next app with react",
};

export default function RootLayout({ children }) {
  // if (typeof window !== "undefined") {
  //   const cookieValue = GetCookieValue();
  //   setupWebSocket(cookieValue);
  // }

  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
